[package]
name = "single-server-queueing-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.18"
rand = "0.8.5"
rand_distr = "0.4.3"
